# Generated by Django 3.0.3 on 2020-02-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_power', models.FloatField()),
                ('energy_today', models.FloatField()),
                ('energy_lifetime', models.FloatField()),
                ('summary_date', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('temp', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('clouds', models.IntegerField()),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
