# Generated by Django 3.0.3 on 2020-04-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200303_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solar',
            name='time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
